@extends('cpanel.layout')
@section('content')
    @if (count($ib_accounts) < 1)
        <div class="row mb-3">
            <div class="col-md-12">
                <div class="card bg-grey">
                    <div class="card-body forexaccountERros">
                        <h5>You Don't Have Any IB Accounts</h5>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="referral-system">
                            <h6>What's "My Referral Link"?</h6>
                            <p>My Referral Link is a unique link generated by our system that identifies who you are. This way, we can give you credit when a friend or colleague becomes a Constant Contact customer. <b>Here's how you can use your unique referral link:</b></p>
                            <ul>
                                <li>Copy and send the link in a regular personal email.</li>
                                <li>Include the link in your email signature.</li>
                                <li>Place the link on your website for your site visitors.</li>
                            </ul>

                            <p>No matter how you share, be sure to have your friend click on your specific link so we can make sure that you get the credit. If they then become Constant Contact customers, you both get account credits!</p>

                            <div class="copylink mn-btn">
                                <input class="form-control-" type="text" id="MyRef" value="https://www.jmibrokers.com/en/signup?myref={{ $user->id + 10000 }}">
                                <button class="sm" onclick="CopyText()">Copy Link</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif

    @section('script')
        <script type="text/javascript">
            function CopyText() {
                $('input#MyRef').val('https://www.jmibrokers.com/en/signup?myref={{ $user->id + 10000 }}');
                var copyText = document.getElementById("MyRef");
                copyText.select();
                document.execCommand("Copy");
            }
        </script>
    @stop
@stop
